defaults: &defaults
  client_id: <%= ENV['CLIENT_ID'] %>
  client_secret: <%= ENV['CLIENT_SECRET'] %>
  account_key: <%= ENV['ACCOUNT_KEY'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

